from __future__ import annotations

from collections import Counter
from typing import Any

from backend.providers.base import ProviderAdapter, ProviderResult


class MockProviderAdapter(ProviderAdapter):
    async def analyze_image(self, payload: dict[str, Any]) -> ProviderResult:
        filename = (payload.get("filename") or "item").lower()
        hints = payload.get("hints") or {}
        category = payload.get("category") or hints.get("category") or self._guess_category(filename)
        color = payload.get("color") or hints.get("color") or self._guess_color(filename)
        season = payload.get("season") or hints.get("season") or "all-season"
        occasion = payload.get("occasion") or hints.get("occasion") or "casual"
        name = self._make_name(category, color)
        item = {
            "name": name,
            "category": category,
            "color": color,
            "season": season,
            "occasion": occasion,
            "notes": payload.get("notes") or "Generated by the local mock provider.",
        }
        return ProviderResult(
            provider=self.id,
            model=self.model or "mock",
            configured=True,
            payload={"confidence": 0.82, "item": item},
            raw={"source": "mock"},
        )

    async def suggest_outfit(self, payload: dict[str, Any]) -> ProviderResult:
        wardrobe_items = payload.get("wardrobeItems") or []
        canvas_items = payload.get("canvasItems") or []
        context = payload.get("context") or {}
        limit = int(payload.get("limit") or 3)
        categories = Counter(item.get("category", "item") for item in wardrobe_items)
        top_category = categories.most_common(1)[0][0] if categories else "tops"
        suggestions: list[dict[str, Any]] = []
        base_items = canvas_items or wardrobe_items[: min(len(wardrobe_items), 4)]
        for index in range(min(limit, max(1, len(base_items)))):
            source = wardrobe_items[index % len(wardrobe_items)] if wardrobe_items else {}
            item_id = source.get("id") or f"mock_{index + 1}"
            suggestions.append(
                {
                    "id": f"mock_suggestion_{index + 1}",
                    "title": f"{context.get('occasion', 'Daily')} {top_category.title()} Look",
                    "itemIds": [item_id],
                    "score": max(72, 92 - index * 4),
                    "reason": self._reason(source, context),
                    "layoutHints": [
                        {
                            "itemId": item_id,
                            "x": 0.2 + index * 0.04,
                            "y": 0.18 + index * 0.03,
                            "width": 0.28,
                            "height": 0.28,
                            "rotation": 0,
                            "zIndex": index + 1,
                        }
                    ],
                }
            )
        return ProviderResult(
            provider=self.id,
            model=self.model or "mock",
            configured=True,
            payload={"suggestions": suggestions},
            raw={"source": "mock"},
        )

    def _guess_category(self, filename: str) -> str:
        if any(token in filename for token in ["pant", "jean", "jeans", "trouser"]):
            return "bottoms"
        if any(token in filename for token in ["shoe", "sneaker"]):
            return "shoes"
        if any(token in filename for token in ["dress", "skirt"]):
            return "one-piece"
        return "tops"

    def _guess_color(self, filename: str) -> str:
        palette = ["black", "white", "blue", "gray", "beige", "green", "red"]
        for color in palette:
            if color in filename:
                return color
        return "neutral"

    def _make_name(self, category: str, color: str) -> str:
        return f"{color.replace('-', ' ').title()} {category.replace('-', ' ').title()}"

    def _reason(self, source: dict[str, Any], context: dict[str, Any]) -> str:
        occasion = context.get("occasion", "daily")
        color = source.get("color", "neutral")
        category = source.get("category", "item")
        return f"Good fit for {occasion} wear with a {color} {category} as the anchor."

